/* 
 * My API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Playground.Api.Client.Client.OpenAPIDateConverter;

namespace Playground.Api.Client.Model
{
    /// <summary>
    /// Defines SubscriptionTypes
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum SubscriptionTypes
    {
        /// <summary>
        /// Enum TwoOfEach for value: TwoOfEach
        /// </summary>
        [EnumMember(Value = "TwoOfEach")]
        TwoOfEach = 1,

        /// <summary>
        /// Enum LimitedHealthCheck for value: LimitedHealthCheck
        /// </summary>
        [EnumMember(Value = "LimitedHealthCheck")]
        LimitedHealthCheck = 2

    }

}
