/* 
 * My API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Playground.Api.Client.Client;
using Playground.Api.Client.Model;

namespace Playground.Api.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IConfigurationApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get a paged result of configurations
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumber"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <returns>List&lt;ConfigurationView&gt;</returns>
        List<ConfigurationView> ApiConfigurationGet (int? pageNumber = default(int?), int? pageSize = default(int?));

        /// <summary>
        /// Get a paged result of configurations
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumber"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <returns>ApiResponse of List&lt;ConfigurationView&gt;</returns>
        ApiResponse<List<ConfigurationView>> ApiConfigurationGetWithHttpInfo (int? pageNumber = default(int?), int? pageSize = default(int?));
        /// <summary>
        /// Get configuration
        /// </summary>
        /// <remarks>
        /// Gets the configuration by the GUID id returned at creation
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ConfigurationView</returns>
        ConfigurationView ApiConfigurationIdGet (Guid id);

        /// <summary>
        /// Get configuration
        /// </summary>
        /// <remarks>
        /// Gets the configuration by the GUID id returned at creation
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of ConfigurationView</returns>
        ApiResponse<ConfigurationView> ApiConfigurationIdGetWithHttpInfo (Guid id);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateConfigurationCommand"> (optional)</param>
        /// <returns></returns>
        void ApiConfigurationIdPatch (string id, UpdateConfigurationCommand updateConfigurationCommand = default(UpdateConfigurationCommand));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateConfigurationCommand"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiConfigurationIdPatchWithHttpInfo (string id, UpdateConfigurationCommand updateConfigurationCommand = default(UpdateConfigurationCommand));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateConfigurationCommand"> (optional)</param>
        /// <returns></returns>
        void ApiConfigurationIdPost (string id, UpdateConfigurationCommand updateConfigurationCommand = default(UpdateConfigurationCommand));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateConfigurationCommand"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ApiConfigurationIdPostWithHttpInfo (string id, UpdateConfigurationCommand updateConfigurationCommand = default(UpdateConfigurationCommand));
        /// <summary>
        /// Create new configuration
        /// </summary>
        /// <remarks>
        /// Used to create an entirely new configuration item:
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createConfigurationCommand"> (optional)</param>
        /// <returns>Guid</returns>
        Guid ApiConfigurationPost (CreateConfigurationCommand createConfigurationCommand = default(CreateConfigurationCommand));

        /// <summary>
        /// Create new configuration
        /// </summary>
        /// <remarks>
        /// Used to create an entirely new configuration item:
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createConfigurationCommand"> (optional)</param>
        /// <returns>ApiResponse of Guid</returns>
        ApiResponse<Guid> ApiConfigurationPostWithHttpInfo (CreateConfigurationCommand createConfigurationCommand = default(CreateConfigurationCommand));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IConfigurationApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get a paged result of configurations
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumber"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <returns>Task of List&lt;ConfigurationView&gt;</returns>
        System.Threading.Tasks.Task<List<ConfigurationView>> ApiConfigurationGetAsync (int? pageNumber = default(int?), int? pageSize = default(int?));

        /// <summary>
        /// Get a paged result of configurations
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumber"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;ConfigurationView&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ConfigurationView>>> ApiConfigurationGetAsyncWithHttpInfo (int? pageNumber = default(int?), int? pageSize = default(int?));
        /// <summary>
        /// Get configuration
        /// </summary>
        /// <remarks>
        /// Gets the configuration by the GUID id returned at creation
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of ConfigurationView</returns>
        System.Threading.Tasks.Task<ConfigurationView> ApiConfigurationIdGetAsync (Guid id);

        /// <summary>
        /// Get configuration
        /// </summary>
        /// <remarks>
        /// Gets the configuration by the GUID id returned at creation
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of ApiResponse (ConfigurationView)</returns>
        System.Threading.Tasks.Task<ApiResponse<ConfigurationView>> ApiConfigurationIdGetAsyncWithHttpInfo (Guid id);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateConfigurationCommand"> (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiConfigurationIdPatchAsync (string id, UpdateConfigurationCommand updateConfigurationCommand = default(UpdateConfigurationCommand));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateConfigurationCommand"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiConfigurationIdPatchAsyncWithHttpInfo (string id, UpdateConfigurationCommand updateConfigurationCommand = default(UpdateConfigurationCommand));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateConfigurationCommand"> (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ApiConfigurationIdPostAsync (string id, UpdateConfigurationCommand updateConfigurationCommand = default(UpdateConfigurationCommand));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateConfigurationCommand"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ApiConfigurationIdPostAsyncWithHttpInfo (string id, UpdateConfigurationCommand updateConfigurationCommand = default(UpdateConfigurationCommand));
        /// <summary>
        /// Create new configuration
        /// </summary>
        /// <remarks>
        /// Used to create an entirely new configuration item:
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createConfigurationCommand"> (optional)</param>
        /// <returns>Task of Guid</returns>
        System.Threading.Tasks.Task<Guid> ApiConfigurationPostAsync (CreateConfigurationCommand createConfigurationCommand = default(CreateConfigurationCommand));

        /// <summary>
        /// Create new configuration
        /// </summary>
        /// <remarks>
        /// Used to create an entirely new configuration item:
        /// </remarks>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createConfigurationCommand"> (optional)</param>
        /// <returns>Task of ApiResponse (Guid)</returns>
        System.Threading.Tasks.Task<ApiResponse<Guid>> ApiConfigurationPostAsyncWithHttpInfo (CreateConfigurationCommand createConfigurationCommand = default(CreateConfigurationCommand));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IConfigurationApi : IConfigurationApiSync, IConfigurationApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ConfigurationApi : IConfigurationApi
    {
        private Playground.Api.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ConfigurationApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ConfigurationApi(String basePath)
        {
            this.Configuration = Playground.Api.Client.Client.Configuration.MergeConfigurations(
                Playground.Api.Client.Client.GlobalConfiguration.Instance,
                new Playground.Api.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Playground.Api.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Playground.Api.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Playground.Api.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ConfigurationApi(Playground.Api.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Playground.Api.Client.Client.Configuration.MergeConfigurations(
                Playground.Api.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Playground.Api.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Playground.Api.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Playground.Api.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ConfigurationApi(Playground.Api.Client.Client.ISynchronousClient client,Playground.Api.Client.Client.IAsynchronousClient asyncClient, Playground.Api.Client.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Playground.Api.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Playground.Api.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Playground.Api.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Playground.Api.Client.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Playground.Api.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get a paged result of configurations 
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumber"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <returns>List&lt;ConfigurationView&gt;</returns>
        public List<ConfigurationView> ApiConfigurationGet (int? pageNumber = default(int?), int? pageSize = default(int?))
        {
             Playground.Api.Client.Client.ApiResponse<List<ConfigurationView>> localVarResponse = ApiConfigurationGetWithHttpInfo(pageNumber, pageSize);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a paged result of configurations 
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumber"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <returns>ApiResponse of List&lt;ConfigurationView&gt;</returns>
        public Playground.Api.Client.Client.ApiResponse< List<ConfigurationView> > ApiConfigurationGetWithHttpInfo (int? pageNumber = default(int?), int? pageSize = default(int?))
        {
            Playground.Api.Client.Client.RequestOptions localVarRequestOptions = new Playground.Api.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Playground.Api.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Playground.Api.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (pageNumber != null)
            {
                foreach (var _kvp in Playground.Api.Client.Client.ClientUtils.ParameterToMultiMap("", "PageNumber", pageNumber))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (pageSize != null)
            {
                foreach (var _kvp in Playground.Api.Client.Client.ClientUtils.ParameterToMultiMap("", "PageSize", pageSize))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get< List<ConfigurationView> >("/api/Configuration", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiConfigurationGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a paged result of configurations 
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumber"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <returns>Task of List&lt;ConfigurationView&gt;</returns>
        public async System.Threading.Tasks.Task<List<ConfigurationView>> ApiConfigurationGetAsync (int? pageNumber = default(int?), int? pageSize = default(int?))
        {
             Playground.Api.Client.Client.ApiResponse<List<ConfigurationView>> localVarResponse = await ApiConfigurationGetAsyncWithHttpInfo(pageNumber, pageSize);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a paged result of configurations 
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageNumber"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;ConfigurationView&gt;)</returns>
        public async System.Threading.Tasks.Task<Playground.Api.Client.Client.ApiResponse<List<ConfigurationView>>> ApiConfigurationGetAsyncWithHttpInfo (int? pageNumber = default(int?), int? pageSize = default(int?))
        {

            Playground.Api.Client.Client.RequestOptions localVarRequestOptions = new Playground.Api.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (pageNumber != null)
            {
                foreach (var _kvp in Playground.Api.Client.Client.ClientUtils.ParameterToMultiMap("", "PageNumber", pageNumber))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (pageSize != null)
            {
                foreach (var _kvp in Playground.Api.Client.Client.ClientUtils.ParameterToMultiMap("", "PageSize", pageSize))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<ConfigurationView>>("/api/Configuration", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiConfigurationGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get configuration Gets the configuration by the GUID id returned at creation
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ConfigurationView</returns>
        public ConfigurationView ApiConfigurationIdGet (Guid id)
        {
             Playground.Api.Client.Client.ApiResponse<ConfigurationView> localVarResponse = ApiConfigurationIdGetWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get configuration Gets the configuration by the GUID id returned at creation
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of ConfigurationView</returns>
        public Playground.Api.Client.Client.ApiResponse< ConfigurationView > ApiConfigurationIdGetWithHttpInfo (Guid id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Playground.Api.Client.Client.ApiException(400, "Missing required parameter 'id' when calling ConfigurationApi->ApiConfigurationIdGet");

            Playground.Api.Client.Client.RequestOptions localVarRequestOptions = new Playground.Api.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Playground.Api.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Playground.Api.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (id != null)
                localVarRequestOptions.PathParameters.Add("id", Playground.Api.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get< ConfigurationView >("/api/Configuration/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiConfigurationIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get configuration Gets the configuration by the GUID id returned at creation
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of ConfigurationView</returns>
        public async System.Threading.Tasks.Task<ConfigurationView> ApiConfigurationIdGetAsync (Guid id)
        {
             Playground.Api.Client.Client.ApiResponse<ConfigurationView> localVarResponse = await ApiConfigurationIdGetAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get configuration Gets the configuration by the GUID id returned at creation
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of ApiResponse (ConfigurationView)</returns>
        public async System.Threading.Tasks.Task<Playground.Api.Client.Client.ApiResponse<ConfigurationView>> ApiConfigurationIdGetAsyncWithHttpInfo (Guid id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Playground.Api.Client.Client.ApiException(400, "Missing required parameter 'id' when calling ConfigurationApi->ApiConfigurationIdGet");


            Playground.Api.Client.Client.RequestOptions localVarRequestOptions = new Playground.Api.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (id != null)
                localVarRequestOptions.PathParameters.Add("id", Playground.Api.Client.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ConfigurationView>("/api/Configuration/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiConfigurationIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateConfigurationCommand"> (optional)</param>
        /// <returns></returns>
        public void ApiConfigurationIdPatch (string id, UpdateConfigurationCommand updateConfigurationCommand = default(UpdateConfigurationCommand))
        {
             ApiConfigurationIdPatchWithHttpInfo(id, updateConfigurationCommand);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateConfigurationCommand"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Playground.Api.Client.Client.ApiResponse<Object> ApiConfigurationIdPatchWithHttpInfo (string id, UpdateConfigurationCommand updateConfigurationCommand = default(UpdateConfigurationCommand))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Playground.Api.Client.Client.ApiException(400, "Missing required parameter 'id' when calling ConfigurationApi->ApiConfigurationIdPatch");

            Playground.Api.Client.Client.RequestOptions localVarRequestOptions = new Playground.Api.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json", 
                "application/json-patch+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Playground.Api.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Playground.Api.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (id != null)
                localVarRequestOptions.PathParameters.Add("id", Playground.Api.Client.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = updateConfigurationCommand;


            // make the HTTP request
            var localVarResponse = this.Client.Patch<Object>("/api/Configuration/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiConfigurationIdPatch", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateConfigurationCommand"> (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiConfigurationIdPatchAsync (string id, UpdateConfigurationCommand updateConfigurationCommand = default(UpdateConfigurationCommand))
        {
             await ApiConfigurationIdPatchAsyncWithHttpInfo(id, updateConfigurationCommand);

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateConfigurationCommand"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Playground.Api.Client.Client.ApiResponse<Object>> ApiConfigurationIdPatchAsyncWithHttpInfo (string id, UpdateConfigurationCommand updateConfigurationCommand = default(UpdateConfigurationCommand))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Playground.Api.Client.Client.ApiException(400, "Missing required parameter 'id' when calling ConfigurationApi->ApiConfigurationIdPatch");


            Playground.Api.Client.Client.RequestOptions localVarRequestOptions = new Playground.Api.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json", 
                "application/json-patch+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (id != null)
                localVarRequestOptions.PathParameters.Add("id", Playground.Api.Client.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = updateConfigurationCommand;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PatchAsync<Object>("/api/Configuration/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiConfigurationIdPatch", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateConfigurationCommand"> (optional)</param>
        /// <returns></returns>
        public void ApiConfigurationIdPost (string id, UpdateConfigurationCommand updateConfigurationCommand = default(UpdateConfigurationCommand))
        {
             ApiConfigurationIdPostWithHttpInfo(id, updateConfigurationCommand);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateConfigurationCommand"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Playground.Api.Client.Client.ApiResponse<Object> ApiConfigurationIdPostWithHttpInfo (string id, UpdateConfigurationCommand updateConfigurationCommand = default(UpdateConfigurationCommand))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Playground.Api.Client.Client.ApiException(400, "Missing required parameter 'id' when calling ConfigurationApi->ApiConfigurationIdPost");

            Playground.Api.Client.Client.RequestOptions localVarRequestOptions = new Playground.Api.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json", 
                "application/json-patch+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Playground.Api.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Playground.Api.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (id != null)
                localVarRequestOptions.PathParameters.Add("id", Playground.Api.Client.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = updateConfigurationCommand;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/api/Configuration/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiConfigurationIdPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateConfigurationCommand"> (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ApiConfigurationIdPostAsync (string id, UpdateConfigurationCommand updateConfigurationCommand = default(UpdateConfigurationCommand))
        {
             await ApiConfigurationIdPostAsyncWithHttpInfo(id, updateConfigurationCommand);

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="updateConfigurationCommand"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Playground.Api.Client.Client.ApiResponse<Object>> ApiConfigurationIdPostAsyncWithHttpInfo (string id, UpdateConfigurationCommand updateConfigurationCommand = default(UpdateConfigurationCommand))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Playground.Api.Client.Client.ApiException(400, "Missing required parameter 'id' when calling ConfigurationApi->ApiConfigurationIdPost");


            Playground.Api.Client.Client.RequestOptions localVarRequestOptions = new Playground.Api.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json", 
                "application/json-patch+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (id != null)
                localVarRequestOptions.PathParameters.Add("id", Playground.Api.Client.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = updateConfigurationCommand;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/api/Configuration/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiConfigurationIdPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create new configuration Used to create an entirely new configuration item:
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createConfigurationCommand"> (optional)</param>
        /// <returns>Guid</returns>
        public Guid ApiConfigurationPost (CreateConfigurationCommand createConfigurationCommand = default(CreateConfigurationCommand))
        {
             Playground.Api.Client.Client.ApiResponse<Guid> localVarResponse = ApiConfigurationPostWithHttpInfo(createConfigurationCommand);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create new configuration Used to create an entirely new configuration item:
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createConfigurationCommand"> (optional)</param>
        /// <returns>ApiResponse of Guid</returns>
        public Playground.Api.Client.Client.ApiResponse< Guid > ApiConfigurationPostWithHttpInfo (CreateConfigurationCommand createConfigurationCommand = default(CreateConfigurationCommand))
        {
            Playground.Api.Client.Client.RequestOptions localVarRequestOptions = new Playground.Api.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json", 
                "application/json-patch+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Playground.Api.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Playground.Api.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createConfigurationCommand;


            // make the HTTP request
            var localVarResponse = this.Client.Post< Guid >("/api/Configuration", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiConfigurationPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create new configuration Used to create an entirely new configuration item:
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createConfigurationCommand"> (optional)</param>
        /// <returns>Task of Guid</returns>
        public async System.Threading.Tasks.Task<Guid> ApiConfigurationPostAsync (CreateConfigurationCommand createConfigurationCommand = default(CreateConfigurationCommand))
        {
             Playground.Api.Client.Client.ApiResponse<Guid> localVarResponse = await ApiConfigurationPostAsyncWithHttpInfo(createConfigurationCommand);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create new configuration Used to create an entirely new configuration item:
        /// </summary>
        /// <exception cref="Playground.Api.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createConfigurationCommand"> (optional)</param>
        /// <returns>Task of ApiResponse (Guid)</returns>
        public async System.Threading.Tasks.Task<Playground.Api.Client.Client.ApiResponse<Guid>> ApiConfigurationPostAsyncWithHttpInfo (CreateConfigurationCommand createConfigurationCommand = default(CreateConfigurationCommand))
        {

            Playground.Api.Client.Client.RequestOptions localVarRequestOptions = new Playground.Api.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json", 
                "application/json-patch+json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.Data = createConfigurationCommand;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Guid>("/api/Configuration", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiConfigurationPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
